---
abstract: 'webify your CLI'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::Differences: '0.64'
  Test::TinyMocker: '0.03'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Module::Install version 1.18, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Wax
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Sereal: '3.015'
requires:
  Digest::SHA: '0'
  File::BaseDir: '0.07'
  File::Slurper: '0.012'
  HTTP::Message: '6.14'
  IPC::System::Simple: '1.25'
  LWP: '6.31'
  MIME::Types: '2.17'
  Method::Signatures::Simple: '1.07'
  Mouse: v2.5.2
  Parallel::parallel_map: '0.02'
  Try::Tiny: '0.30'
  URI: '1.73'
  perl: '5.008008'
resources:
  bugtracker: https://github.com/chocolateboy/App-Wax/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/chocolateboy/App-Wax
version: 2.1.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
