---
abstract: 'webify your CLI'
author:
  - 'chocolateboy <chocolate@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Differences: 0.63
  Test::Fatal: 0.014
  Test::TinyMocker: 0.03
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Wax
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Sereal: 3.005
requires:
  Digest::SHA: 0
  File::Slurp: 9999.19
  HTTP::Message: 6.06
  IPC::System::Simple: 1.25
  LWP: 6.08
  MIME::Types: 2.09
  Method::Signatures::Simple: 1.07
  Mouse: 2.4.1
  Parallel::parallel_map: 0.02
  Try::Tiny: 0.22
  URI: 1.65
  perl: 5.8.8
resources:
  bugtracker: https://github.com/chocolateboy/App-Wax/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/chocolateboy/App-Wax
version: 1.0.3
